name = "parivarthan-backend"
main = "src/main.py"
compatibility_date = "2026-01-01"
compatibility_flags = ["python_workers"]

[observability]
enabled = true

[env.production]
name = "parivarthan-backend-production"
