"""p3_schema_extensions

Revision ID: 60775f9338d3
Revises: e8a1523b2f3a
Create Date: 2026-05-02 15:48:51.003301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60775f9338d3'
down_revision: Union[str, Sequence[str], None] = 'e8a1523b2f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_invite_tokens',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('hc_user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hc_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_invite_tokens_client_id', 'client_invite_tokens', ['client_id'], unique=False)
    op.add_column('clients', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(None, 'clients', ['user_id'])
    op.create_foreign_key(None, 'clients', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('sessions', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('users', sa.Column('role', sa.Text(), server_default=sa.text("'hc'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('sessions', 'deleted_at')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('clients', 'user_id')
    op.drop_index('idx_invite_tokens_client_id', table_name='client_invite_tokens')
    op.drop_table('client_invite_tokens')
    # ### end Alembic commands ###
