"""initial_schema

Revision ID: e8a1523b2f3a
Revises: 
Create Date: 2026-04-30 19:20:32.027364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8a1523b2f3a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('google_sub', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('is_operator', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_table', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('target_hc_user_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_target', 'audit_log', ['target_hc_user_id', 'created_at'], unique=False)
    op.create_table('auth_refresh_tokens',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('issued_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('successor_id', sa.Uuid(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_at_issue', postgresql.INET(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['successor_id'], ['auth_refresh_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_refresh_tokens_active', 'auth_refresh_tokens', ['user_id'], unique=False, postgresql_where='revoked_at IS NULL')
    op.create_index('idx_refresh_tokens_token_hash', 'auth_refresh_tokens', ['token_hash'], unique=False)
    op.create_index('idx_refresh_tokens_user_id', 'auth_refresh_tokens', ['user_id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hc_user_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.Column('journey_stage', sa.Text(), server_default='onboarding', nullable=False),
    sa.Column('course_start_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('course_end_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('course_goal', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hc_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_clients_hc_user_id', 'clients', ['hc_user_id'], unique=False)
    op.create_index('idx_clients_journey_stage', 'clients', ['hc_user_id', 'journey_stage'], unique=False)
    op.create_table('diet_charts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hc_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hc_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_diet_charts_hc_user_id', 'diet_charts', ['hc_user_id'], unique=False, postgresql_where='archived_at IS NULL')
    op.create_table('prep_recipes',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hc_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hc_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prep_recipes_hc_user_id', 'prep_recipes', ['hc_user_id'], unique=False, postgresql_where='archived_at IS NULL')
    op.create_table('check_ins',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('hc_user_id', sa.Uuid(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sentiment_flag', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hc_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_check_ins_client_created', 'check_ins', ['client_id', 'created_at'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('hc_user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_artifact_s3_key', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hc_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consents_client_purpose', 'consents', ['client_id', 'purpose'], unique=False)
    op.create_table('diet_chart_recipes',
    sa.Column('diet_chart_id', sa.Uuid(), nullable=False),
    sa.Column('prep_recipe_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['diet_chart_id'], ['diet_charts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prep_recipe_id'], ['prep_recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('diet_chart_id', 'prep_recipe_id')
    )
    op.create_table('hc_style_snippets',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hc_user_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('snippet_type', sa.Text(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('hc_modified_text', sa.Text(), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('retired_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('relevance_tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('use_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hc_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snippets_client_id', 'hc_style_snippets', ['client_id'], unique=False)
    op.create_index('idx_snippets_hc_user_id', 'hc_style_snippets', ['hc_user_id'], unique=False)
    op.create_index('idx_snippets_last_used', 'hc_style_snippets', ['hc_user_id', 'last_used_at'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hc_user_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('zoom_meeting_id', sa.Text(), nullable=True),
    sa.Column('transcript_s3_key', sa.Text(), nullable=True),
    sa.Column('summary_s3_key', sa.Text(), nullable=True),
    sa.Column('notes_internal', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hc_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'session_number', name='idx_sessions_client_session_number')
    )
    op.create_index('idx_sessions_client_id', 'sessions', ['client_id'], unique=False)
    op.create_index('idx_sessions_hc_user_id_scheduled', 'sessions', ['hc_user_id', 'scheduled_at'], unique=False)
    op.create_table('action_items',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('hc_user_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), server_default='open', nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hc_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_action_items_client_status', 'action_items', ['client_id', 'status'], unique=False)
    op.create_table('content_assignments',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hc_user_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hc_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_content_assignments_client', 'content_assignments', ['client_id', 'assigned_at'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hc_user_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('use_case', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('model_requested', sa.Text(), nullable=False),
    sa.Column('model_served', sa.Text(), nullable=True),
    sa.Column('fallback_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('validation_failed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('snippet_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('snippet_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('inr_cost_estimate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('raw_request_id', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['hc_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_llm_calls_created_at', 'llm_calls', ['created_at'], unique=False)
    op.create_index('idx_llm_calls_hc_use_case', 'llm_calls', ['hc_user_id', 'use_case'], unique=False)
    op.create_index('idx_llm_calls_validation_failed', 'llm_calls', ['validation_failed'], unique=False, postgresql_where='validation_failed = TRUE')
    op.create_table('briefs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('hc_user_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('brief_text', sa.Text(), nullable=False),
    sa.Column('triage_flags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('llm_call_id', sa.Uuid(), nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hc_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_calls.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('idx_briefs_session_id', 'briefs', ['session_id'], unique=False)
    op.create_table('moms',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('hc_user_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('final_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('sent_to_email', sa.Text(), nullable=True),
    sa.Column('llm_call_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hc_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_calls.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('idx_moms_client_id', 'moms', ['client_id'], unique=False)
    op.create_index('idx_moms_status', 'moms', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_moms_status', table_name='moms')
    op.drop_index('idx_moms_client_id', table_name='moms')
    op.drop_table('moms')
    op.drop_index('idx_briefs_session_id', table_name='briefs')
    op.drop_table('briefs')
    op.drop_index('idx_llm_calls_validation_failed', table_name='llm_calls', postgresql_where='validation_failed = TRUE')
    op.drop_index('idx_llm_calls_hc_use_case', table_name='llm_calls')
    op.drop_index('idx_llm_calls_created_at', table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index('idx_content_assignments_client', table_name='content_assignments')
    op.drop_table('content_assignments')
    op.drop_index('idx_action_items_client_status', table_name='action_items')
    op.drop_table('action_items')
    op.drop_index('idx_sessions_hc_user_id_scheduled', table_name='sessions')
    op.drop_index('idx_sessions_client_id', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_snippets_last_used', table_name='hc_style_snippets')
    op.drop_index('idx_snippets_hc_user_id', table_name='hc_style_snippets')
    op.drop_index('idx_snippets_client_id', table_name='hc_style_snippets')
    op.drop_table('hc_style_snippets')
    op.drop_table('diet_chart_recipes')
    op.drop_index('idx_consents_client_purpose', table_name='consents')
    op.drop_table('consents')
    op.drop_index('idx_check_ins_client_created', table_name='check_ins')
    op.drop_table('check_ins')
    op.drop_index('idx_prep_recipes_hc_user_id', table_name='prep_recipes', postgresql_where='archived_at IS NULL')
    op.drop_table('prep_recipes')
    op.drop_index('idx_diet_charts_hc_user_id', table_name='diet_charts', postgresql_where='archived_at IS NULL')
    op.drop_table('diet_charts')
    op.drop_index('idx_clients_journey_stage', table_name='clients')
    op.drop_index('idx_clients_hc_user_id', table_name='clients')
    op.drop_table('clients')
    op.drop_index('idx_refresh_tokens_user_id', table_name='auth_refresh_tokens')
    op.drop_index('idx_refresh_tokens_token_hash', table_name='auth_refresh_tokens')
    op.drop_index('idx_refresh_tokens_active', table_name='auth_refresh_tokens', postgresql_where='revoked_at IS NULL')
    op.drop_table('auth_refresh_tokens')
    op.drop_index('idx_audit_log_target', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('users')
    # ### end Alembic commands ###
